Added ldap check to autoconf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -813,6 +813,7 @@ Optional Packages:
   --with-mail_local=DIR   path to mail.local
   --with-procmail=DIR     path to procmail
   --with-db=DIR           path to db
+  --with-ldap=DIR         path to ldap
   --with-ssl=DIR          path to ssl
 
 Some influential environment variables:
@@ -2731,6 +2732,99 @@ echo "$as_me: error: cannot find db " >&2;}
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
+
+
+echo "$as_me:$LINENO: checking for ldap_init in -lldap" >&5
+echo $ECHO_N "checking for ldap_init in -lldap... $ECHO_C" >&6
+if test "${ac_cv_lib_ldap_ldap_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lldap  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char ldap_init ();
+int
+main ()
+{
+ldap_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ldap_ldap_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_ldap_ldap_init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ldap_ldap_init" >&5
+echo "${ECHO_T}$ac_cv_lib_ldap_ldap_init" >&6
+if test $ac_cv_lib_ldap_ldap_init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLDAP 1
+_ACEOF
+
+  LIBS="-lldap $LIBS"
+
+else
+
+    echo "$as_me:$LINENO: checking for ldap" >&5
+echo $ECHO_N "checking for ldap... $ECHO_C" >&6
+    ldapdirs="/usr"
+
+# Check whether --with-ldap or --without-ldap was given.
+if test "${with_ldap+set}" = set; then
+  withval="$with_ldap"
+  ldapdirs="$withval"
+fi;
+    found_ldap="no";
+    for dir in $ldapdirs; do
+	ldapdir="$dir"
+	if test -f "$dir/include/ldap.h"; then
+	    found_ldap="yes";
+	    break;
+	fi
+    done
+    if test x_$found_ldap != x_yes; then
+	{ { echo "$as_me:$LINENO: error: cannot find ldap libraries" >&5
+echo "$as_me: error: cannot find ldap libraries" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+	LIBS="$LIBS -lldap";
+    fi
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+fi
 
 
 echo "$as_me:$LINENO: checking for SSL_accept in -lssl" >&5
