./configure checks for mail.local. added INSTALL. better test cases / debugging added.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -789,6 +789,7 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-mail_local=DIR   path to mail.local
   --with-ssl=DIR          path to ssl
 
 Some influential environment variables:
@@ -2028,6 +2029,36 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 
+# Find mail.local
+
+    echo "$as_me:$LINENO: checking for mail.local" >&5
+echo $ECHO_N "checking for mail.local... $ECHO_C" >&6
+    mail_local_dirs="/usr/lib /usr/sbin"
+
+# Check whether --with-mail_local or --without-mail_local was given.
+if test "${with_mail_local+set}" = set; then
+  withval="$with_mail_local"
+  mail_local_dirs="$withval"
+fi;
+    for dir in $mail_local_dirs; do
+	mail_local_dir="$dir"
+	if test -f "$dir/mail.local"; then
+	    found_mail_local="yes";
+	    break
+	fi
+    done
+    if test x_$found_mail_local != x_yes; then
+	{ { echo "$as_me:$LINENO: error: not found: See INSTALL" >&5
+echo "$as_me: error: not found: See INSTALL" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+	SIMTA_MAIL_LOCAL=$dir/mail.local
+
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    fi
+
+
 if test x_$GCC = x_yes; then
     OPTOPTS=${OPTOPTS:-"-Wall -Wmissing-prototypes -Wconversion"}
 fi
@@ -2910,6 +2941,7 @@ s,@OBJEXT@,$OBJEXT,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
+s,@SIMTA_MAIL_LOCAL@,$SIMTA_MAIL_LOCAL,;t t
 s,@OPTOPTS@,$OPTOPTS,;t t
 s,@HAVE_TM_GMTOFF@,$HAVE_TM_GMTOFF,;t t
 s,@TLSDEFS@,$TLSDEFS,;t t
